---
title: "EDA_Project"
author: "Stanly Wilson Palathingal"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir= normalizePath('..'))
```

Install the required packages only for the first time.
```{r Installation of packages, message=FALSE}
#install.packages("ProjectTemplate")
#install.packages("rmarkdown")
```

```{r Load library and create the project, message=FALSE}
library(ProjectTemplate)
library(rmarkdown)
library(ggplot2)
# create.project("EDA_Project")
load.project()
```


```{r Loading the archetypr datasets}

archetype7= read.csv("data/cyber-security-7_archetype-survey-responses.csv")
archetype6= read.csv("data/cyber-security-6_archetype-survey-responses.csv")
archetype5= read.csv("data/cyber-security-5_archetype-survey-responses.csv")
archetype4= read.csv("data/cyber-security-4_archetype-survey-responses.csv")
archetype3= read.csv("data/cyber-security-3_archetype-survey-responses.csv")

```



```{r extracting the archetype and making new frame}
a7=data.frame("year"= 2017,"learner_id"= archetype7$learner_id,"archetype"= archetype7$archetype)
a6=data.frame("year"= 2016,"learner_id"= archetype6$learner_id,"archetype"= archetype6$archetype)
a5=data.frame("year"= 2015,"learner_id"= archetype5$learner_id,"archetype"= archetype5$archetype)
a4=data.frame("year"= 2014,"learner_id"= archetype4$learner_id,"archetype"= archetype4$archetype)
a3=data.frame("year"= 2013,"learner_id"= archetype3$learner_id,"archetype"= archetype3$archetype)

t=rbind(a3,a4,a5,a6,a7)
head(t)
(total=table(t$archetype))
sum(total)

```


```{r plotting the graph, fig.height=7,fig.width= 14}

ggplot(data=archetype7,aes(archetype7$archetype)) + geom_bar()  

ggplot(data=t) + geom_bar(aes(x=year,fill=factor(archetype))) 

ggplot(data=t) + geom_bar(aes(x=year,fill=factor(archetype)), position = position_dodge(preserve = 'single')) 

```


