---
title: "EDA_Project3"
author: "Stanly Palathingal"
date: "17 November 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir= normalizePath('..'))
```

Install the required packages only for the first time.
```{r Installation of packages, message=FALSE}
#install.packages("ProjectTemplate")
#install.packages("rmarkdown")
#install.packages("dplyr")
```

```{r Load library and create the project, message=FALSE}
library(ProjectTemplate)
library(rmarkdown)
library(dplyr)
library(ggplot2)
# create.project("EDA_Project")
```

```{r Setting of working directory and load project}
load.project()
```


```{r loading the step activity data set}
step_act_7= read.csv("data/cyber-security-7_step-activity.csv")
step_act_6= read.csv("data/cyber-security-6_step-activity.csv")
step_act_5= read.csv("data/cyber-security-5_step-activity.csv")
step_act_4= read.csv("data/cyber-security-4_step-activity.csv")
step_act_3= read.csv("data/cyber-security-3_step-activity.csv")
step_act_2= read.csv("data/cyber-security-2_step-activity.csv")
step_act_1= read.csv("data/cyber-security-1_step-activity.csv")
```


```{r step_act_7,fig.height=4,fig.width=10}
step_7= step_act_7 %>%  group_by(week_number, step_number) %>% count()
data.frame(step_7)
ggplot(data=step_7,aes(x=factor(week_number),y=n,group =step_number)) + geom_line(aes(color =factor(week_number))) + geom_point(aes(color = factor(week_number)))
```
```{r step_act_6,fig.height=4,fig.width=10}
(step_6= step_act_6 %>%  group_by(week_number, step_number) %>% count())

ggplot(data=step_6,aes(x=factor(week_number),y=n,group =step_number)) + geom_line(aes(color =factor(week_number))) + geom_point(aes(color = factor(week_number)))
```

```{r step_act_5,fig.height=4,fig.width=10}
(step_5= step_act_5 %>%  group_by(week_number, step_number) %>% count())

ggplot(data=step_5,aes(x=factor(week_number),y=n,group =step_number)) + geom_line(aes(color =factor(week_number))) + geom_point(aes(color = factor(week_number)))
```

```{r step_act_4,fig.height=4,fig.width=10}
(step_4= step_act_4 %>%  group_by(week_number, step_number) %>% count())

ggplot(data=step_4,aes(x=factor(week_number),y=n,group =step_number)) + geom_line(aes(color =factor(week_number))) + geom_point(aes(color = factor(week_number)))
```

```{r step_act_3,fig.height=4,fig.width=10}
(step_3= step_act_3 %>%  group_by(week_number, step_number) %>% count())

ggplot(data=step_3,aes(x=factor(week_number),y=n,group =step_number)) + geom_line(aes(color =factor(week_number))) + geom_point(aes(color = factor(week_number)))
```

```{r step_act_2,fig.height=4,fig.width=10}
(step_2= step_act_2 %>%  group_by(week_number, step_number) %>% count())

ggplot(data=step_2,aes(x=factor(week_number),y=n,group =step_number)) + geom_line(aes(color =factor(week_number))) + geom_point(aes(color = factor(week_number)))
```

```{r step_act_1,fig.height=4,fig.width=10}
(step_1= step_act_1 %>%  group_by(week_number, step_number) %>% count())

ggplot(data=step_1,aes(x=factor(week_number),y=n,group =step_number)) + geom_line(aes(color =factor(week_number))) + geom_point(aes(color = factor(week_number)))
```
```{r}
step_7_1=step_act_7 %>% select(learner_id) %>% filter(step_act_7$week_number==3 & step_act_7$step_number==18)
st7=data.frame("year"= 2017,"n"= length(step_7_1$learner_id))

step_6_1=step_act_6 %>% select(learner_id) %>% filter(step_act_6$week_number==3 & step_act_6$step_number==18)
st6=data.frame("year"= 2016,"n"= length(step_6_1$learner_id))

step_5_1=step_act_5 %>% select(learner_id) %>% filter(step_act_5$week_number==3 & step_act_5$step_number==18)
st5=data.frame("year"= 2015,"n"= length(step_5_1$learner_id))

step_4_1=step_act_4 %>% select(learner_id) %>% filter(step_act_4$week_number==3 & step_act_4$step_number==18)
st4=data.frame("year"= 2014,"n"= length(step_4_1$learner_id))

step_3_1=step_act_3 %>% select(learner_id) %>% filter(step_act_3$week_number==3 & step_act_3$step_number==18)
st3=data.frame("year"= 2013,"n"= length(step_3_1$learner_id))

step_2_1=step_act_2 %>% select(learner_id) %>% filter(step_act_2$week_number==3 & step_act_2$step_number==18)
st2=data.frame("year"= 2012,"n"= length(step_2_1$learner_id))

step_1_1=step_act_1 %>% select(learner_id) %>% filter(step_act_1$week_number==3 & step_act_1$step_number==18)
st1=data.frame("year"= 2011,"n"= length(step_1_1$learner_id))

step_w3_st18 = rbind(st1,st2,st3,st4,st5,st6,st7)


ggplot(data=step_w3_st18) + geom_bar(aes(x=year,y= n,fill=factor(n)), stat = "identity") +xlab("year")+ ylab("week 3 step 18")

```

